package generate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const (
	// FormatFlux generates Flux HelmReleases and OCIRepositories.
	FormatFlux = "helmrelease"

	generatedLabel = "core.platform-mesh.io/installer-created"

	fileHeader = "# This file was generated by the Platform Mesh installer; do not edit it,\n" +
		"# edit your Helm values and re-run `installer deploy` instead.\n"
)

// Formats returns all supported output formats.
func Formats() []string {
	return []string{FormatFlux}
}

type metadata struct {
	Name      string            `yaml:"name"`
	Namespace string            `yaml:"namespace"`
	Labels    map[string]string `yaml:"labels,omitempty"`
}

type ociRepository struct {
	APIVersion string            `yaml:"apiVersion"`
	Kind       string            `yaml:"kind"`
	Metadata   metadata          `yaml:"metadata"`
	Spec       ociRepositorySpec `yaml:"spec"`
}

type ociRepositorySpec struct {
	Interval      string        `yaml:"interval"`
	LayerSelector layerSelector `yaml:"layerSelector"`
	Provider      string        `yaml:"provider"`
	Ref           ociRef        `yaml:"ref"`
	Timeout       string        `yaml:"timeout"`
	URL           string        `yaml:"url"`
}

type layerSelector struct {
	MediaType string `yaml:"mediaType"`
	Operation string `yaml:"operation"`
}

type ociRef struct {
	Tag    string `yaml:"tag,omitempty"`
	Digest string `yaml:"digest,omitempty"`
}

type helmRelease struct {
	APIVersion string          `yaml:"apiVersion"`
	Kind       string          `yaml:"kind"`
	Metadata   metadata        `yaml:"metadata"`
	Spec       helmReleaseSpec `yaml:"spec"`
}

type helmReleaseSpec struct {
	ChartRef        chartRef     `yaml:"chartRef"`
	DependsOn       []dependency `yaml:"dependsOn,omitempty"`
	Interval        string       `yaml:"interval"`
	ReleaseName     string       `yaml:"releaseName"`
	TargetNamespace string       `yaml:"targetNamespace"`
	Timeout         string       `yaml:"timeout"`
	Install         remediation  `yaml:"install"`
	Upgrade         remediation  `yaml:"upgrade"`
	Values          *yaml.Node   `yaml:"values,omitempty"`
}

type chartRef struct {
	Kind      string `yaml:"kind"`
	Name      string `yaml:"name"`
	Namespace string `yaml:"namespace"`
}

type dependency struct {
	Name      string `yaml:"name"`
	Namespace string `yaml:"namespace,omitempty"`
}

type remediation struct {
	Remediation retries `yaml:"remediation"`
}

type retries struct {
	Retries int `yaml:"retries"`
}

// FluxWriter writes HelmReleases and OCIRepositories into an output directory.
type FluxWriter struct {
	// Interval is the reconciliation interval for the generated objects.
	Interval string
	// Timeout for Helm operations.
	Timeout string
	// Digests controls whether the OCI digest of a chart is pinned in addition to its tag.
	Digests bool
}

// NewFluxWriter returns a writer with sensible defaults.
func NewFluxWriter() *FluxWriter {
	return &FluxWriter{
		Interval: "1m",
		Timeout:  "15m",
		Digests:  true,
	}
}

// Write creates "<dir>/helmreleases/<name>.yaml" and "<dir>/ocirepositories/<name>.yaml"
// for every release and returns the list of written files.
func (w *FluxWriter) Write(dir string, releases []Release) ([]string, error) {
	helmReleaseDir := filepath.Join(dir, "helmreleases")
	ociRepoDir := filepath.Join(dir, "ocirepositories")

	for _, d := range []string{helmReleaseDir, ociRepoDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return nil, fmt.Errorf("cannot create %q: %w", d, err)
		}
	}

	files := []string{}

	for _, release := range releases {
		repoFile := filepath.Join(ociRepoDir, release.Name+".yaml")
		if err := writeYAML(repoFile, w.ociRepository(release)); err != nil {
			return nil, err
		}

		relFile := filepath.Join(helmReleaseDir, release.Name+".yaml")
		if err := writeYAML(relFile, w.helmRelease(release)); err != nil {
			return nil, err
		}

		files = append(files, repoFile, relFile)
	}

	return files, nil
}

func (w *FluxWriter) ociRepository(release Release) ociRepository {
	// Flux prefers the digest over the tag, but keeping the tag around makes the manifests
	// readable and allows to drop the digest without losing the version information.
	ref := ociRef{Tag: release.ChartVersion}
	if w.Digests {
		ref.Digest = release.ChartDigest
	}

	if ref.Tag == "" && ref.Digest == "" {
		ref.Digest = release.ChartDigest
	}

	return ociRepository{
		APIVersion: "source.toolkit.fluxcd.io/v1",
		Kind:       "OCIRepository",
		Metadata: metadata{
			Name:      release.Name,
			Namespace: release.Namespace,
			Labels:    map[string]string{generatedLabel: "true"},
		},
		Spec: ociRepositorySpec{
			Interval: "1m0s",
			LayerSelector: layerSelector{
				MediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
				Operation: "copy",
			},
			Provider: "generic",
			Ref:      ref,
			Timeout:  "60s",
			URL:      "oci://" + release.ChartURL,
		},
	}
}

func (w *FluxWriter) helmRelease(release Release) helmRelease {
	deps := make([]dependency, 0, len(release.DependsOn))
	for _, dep := range release.DependsOn {
		deps = append(deps, dependency{Name: dep, Namespace: release.Namespace})
	}

	return helmRelease{
		APIVersion: "helm.toolkit.fluxcd.io/v2",
		Kind:       "HelmRelease",
		Metadata: metadata{
			Name:      release.Name,
			Namespace: release.Namespace,
			Labels:    map[string]string{generatedLabel: "true"},
		},
		Spec: helmReleaseSpec{
			ChartRef: chartRef{
				Kind:      "OCIRepository",
				Name:      release.Name,
				Namespace: release.Namespace,
			},
			DependsOn:       deps,
			Interval:        w.Interval,
			ReleaseName:     release.Name,
			TargetNamespace: release.TargetNamespace,
			Timeout:         w.Timeout,
			Install:         remediation{Remediation: retries{Retries: -1}},
			Upgrade:         remediation{Remediation: retries{Retries: 3}},
			Values:          release.Values,
		},
	}
}

func writeYAML(filename string, obj any) error {
	var buf bytes.Buffer

	buf.WriteString(fileHeader)

	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)

	if err := encoder.Encode(obj); err != nil {
		return fmt.Errorf("cannot encode %q: %w", filename, err)
	}

	if err := encoder.Close(); err != nil {
		return fmt.Errorf("cannot encode %q: %w", filename, err)
	}

	if err := os.WriteFile(filename, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("cannot write %q: %w", filename, err)
	}

	return nil
}
