apiVersion: core.platform-mesh.io/v1alpha1
kind: PlatformMesh
metadata:
  annotations: {}
  name: platform-mesh
  namespace: platform-mesh-system
spec:
  exposure:
    baseDomain: PM_BASE_DOMAIN
    kcpFrontProxyClusterIP: FRONT_PROXY_SERVICE_IP
    port: 8443
    protocol: https
    traefikClusterIP: TRAEFIK_SERVICE_IP
  profileConfigMap:
    name: platform-mesh-profile
    namespace: platform-mesh-system
  featureToggles:
    - name: feature-enable-getting-started
    - name: feature-disable-email-verification
    - name: feature-accounts-in-accounts
    - name: feature-enable-provider-permissions
  kcp: {}
  ocm:
    component:
      name: platform-mesh
    referencePath: []
    repo:
      name: platform-mesh
  values:
    services:
      infra:
        values:
          kcp:
            external:
              hostname: kcp.api.PM_BASE_DOMAIN
            rootShard:
              hostname: root.kcp.PM_BASE_DOMAIN
              shardBaseURL: https://root.kcp.PM_BASE_DOMAIN:8443/
            shards:
              - hostname: triton.kcp.PM_BASE_DOMAIN
                name: triton
