apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: platform-mesh-system
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: v1.20.1
  timeout: 60s
  url: oci://quay.io/jetstack/charts/cert-manager
