apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-operator
  namespace: platform-mesh-system
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 0.28.0
  timeout: 60s
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
