apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kcp-operator
  namespace: platform-mesh-system
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 0.7.4
  timeout: 60s
  url: oci://ghcr.io/platform-mesh/helm-charts/charts/mirrored/kcp-operator
