apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
  namespace: platform-mesh-system
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 29.0.0
  timeout: 60s
  url: oci://ghcr.io/platform-mesh/ocm/charts/prometheus-operator-crds
