apiVersion: v1
kind: Secret
metadata:
  name: kcp-webhook-secret
  namespace: platform-mesh-system
type: Opaque
# TODO: Instead of assembling the kubeconfig like this, use paths to an external
# CA file and mount the kubeconfig PLUS the rebac-webhook-cert into whereever they
# are needed. Like kcp does in most places.
# Saves us from having to "manually" create this and to manually rotate, since the
# kcp-operator already would handle it for us.
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        # insert CA from the rebac-webhook-cert here
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lVRUk4cVB6SDh4Z01HVitORXpjdERwWURJQkpVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0FEQWVGdzB5TmpBNU1qSXhPVEV6TWpaYUZ3MHlOakV5TWpFeE9URXpNalphTUFBd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDeFNLMUZLYlh3cVRMR2pkL0JLdm9Td3lTN3phWlpUNnBaClY3NllhUUJRZis5cWlmUHVsMVNjTE5XNXU3OGp0NnM4eTk3M1JoRkUyT3dscWgrcHZJTGtYOFZPOGdsMUUxeHQKaVBhdnI5RGxoYTcrVnFPWFlHbUkyQXUwNFNuVk9waCswZlBhUkdLTzdPK2E4aWtvWWZJMHdRRGI1ZjY5M2JtKwpsSDJaRytITlV5Q2U3Yy85ek8zSE1ld2d5ZnUwZUFZQmhWNU4zYXFXNlcrT3c0RmxDWGRFZVFzekh3Mm9aMHBFCmVQQkdyNXRBWEZhMTZNNCtwaDJDdkxaKzRVc29vRHNNRW56bmwvRXdYb0twVTZxSnA3Ui9rZkU4NllaNklHUG0KRWgzaldaTldlY1FjZThoNEo3S0o5WnBZN0t0bTJ6QTJLamR5TzFRQm1UUi91RXFZTWVmTEFnTUJBQUdqYWpCbwpNQTRHQTFVZER3RUIvd1FFQXdJRm9EQU1CZ05WSFJNQkFmOEVBakFBTUVnR0ExVWRFUUVCL3dRK01EeUNPbkpsClltRmpMV0YxZEdoNkxYZGxZbWh2YjJzdWNHeGhkR1p2Y20wdGJXVnphQzF6ZVhOMFpXMHVjM1pqTG1Oc2RYTjAKWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJhNTg2SStGM3ZHRjBWajYyQUljRG9NbGNuaworRUVIRXN4d3REa2w5dDBzMzhNU2JwNEIxUVczT1BZelhuTXRiLzZHMGwwMXRNT2pXVXlKcmhycEFSdytJdExiClpmQW8zdzhRcWxkZG9JTUxpWDJ5ZGVNblJwaE81T3BMRGhRODR3MjRRL3BtQnRMY2VzZS9pWXArWUdXUG1sSk0KSExrUGhGeGZDeTNxQVBvWUlpMmw1MkZLRmFacnhQZk44RGlVblNLZ1YwOTBNTDJGWFgxbDBQUTBrM2ZObTJOLwpvR0NibVl4bzRZcldJWlFBVlErMm9sUlFWd01XaHR6aW1PVE0wWU4xZUZjbjRSa2FvcHAwREk1UzJYazZtRUlFCitkcm14ODF0ZytOOVJmRDQ3MW01UllaQUpVM1VQZWc1RXEvQTNwb2ZWSWE2K2dCVmVSWjBNSk1seEQwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
        server: https://rebac-authz-webhook.platform-mesh-system.svc.cluster.local:9443/authz
      name: webhook
    contexts:
    - context:
        cluster: webhook
      name: webhook
    current-context: webhook
    kind: Config
