apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: cert-manager
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: cert-manager
  targetNamespace: default
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: true
