apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: etcd-druid
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: etcd-druid
    namespace: platform-mesh-system
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 1m
  releaseName: etcd-druid
  targetNamespace: etcd-druid-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
