apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: extension-manager-operator
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: extension-manager-operator
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: extension-manager-operator
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    # TODO: This controls the extension-manager-operator-crds dependencies, which
    # has resources like APIExports and APIResourceSchemas that belong *inside*
    # kcp. Installing these on the hosting cluster never makes sense.
    # The PM Operator is the component that bootstraps in-kcp stuff.
    # Arguably this flag should default to false or be removed entirely.
    crds:
      enabled: false
    # Mostly performance improvements for routing traffic. Should be able
    # to skip configuring this.
    hostAliases:
      enabled: true
      entries:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
