apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: iam-service
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: iam-service
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: iam-service
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    caSecret: domain-certificate-ca
    exposure:
      hostnames:
        - PM_BASE_DOMAIN
        - '*.PM_BASE_DOMAIN'
    # Mostly performance improvements for routing traffic. Should be able
    # to skip configuring this.
    hostAliases:
      enabled: true
      entries:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
    keycloak:
      baseUrl: https://PM_BASE_DOMAIN:8443/keycloak
