apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: iam-ui
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: iam-ui
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: iam-ui
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    exposure:
      hostnames:
        - pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
        - '*.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com'
