apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: iam-service
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: iam-service
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: iam-service
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    caSecret: domain-certificate-ca
    exposure:
      hostnames:
        - pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
        - '*.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com'
    # Mostly performance improvements for routing traffic. Should be able
    # to skip configuring this.
    hostAliases:
      enabled: true
      entries:
        - ip: 100.104.59.216
          hostnames:
            - pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
            - kcp.api.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
            - root.kcp.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
            - triton.kcp.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
    keycloak:
      baseUrl: https://pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com:8443/keycloak
