apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: infra
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: infra
    namespace: platform-mesh-system
  dependsOn:
    - name: keycloak-operator
      namespace: platform-mesh-system
    - name: cnpg-operator
      namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: infra
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    cnpg:
      enabled: true
    dex:
      enabled: true
      gatewayApi:
        hostnames:
          - PM_BASE_DOMAIN
      issuer: https://PM_BASE_DOMAIN:8443/dex
      staticClient:
        redirectURIs:
          - https://PM_BASE_DOMAIN:8443/keycloak/realms/default/broker/dex/endpoint
    gatewayApi:
      infrastructure:
        annotations:
          dns.gardener.cloud/class: garden
      listeners:
        - name: terminate
          hostname: PM_BASE_DOMAIN
          port: 8443
          protocol: HTTPS
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: domain-certificate
                namespace: platform-mesh-system
        - name: terminate-wildstar
          hostname: "*.PM_BASE_DOMAIN"
          port: 8443
          protocol: HTTPS
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: domain-certificate
                namespace: platform-mesh-system
        - name: passthrough
          port: 8443
          protocol: TLS
          tls:
            mode: Passthrough
          allowedRoutes:
            namespaces:
              from: All
      listenersExtra:
        - name: terminate-services
          hostname: "*.services.PM_BASE_DOMAIN"
          port: 8443
          protocol: HTTPS
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: domain-certificate
                namespace: platform-mesh-system
          allowedRoutes:
            namespaces:
              from: All
    hostAliases:
      enabled: true
      entries:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
    kcp:
      external:
        hostname: kcp.api.PM_BASE_DOMAIN
      frontProxy:
        clusterIP: FRONT_PROXY_SERVICE_IP
      rootShard:
        hostname: root.kcp.PM_BASE_DOMAIN
        shardBaseURL: https://root.kcp.PM_BASE_DOMAIN:8443/
      shards:
        - hostname: triton.kcp.PM_BASE_DOMAIN
          name: triton
    keycloak:
      gatewayApi:
        hostnames:
          - PM_BASE_DOMAIN
      keycloakConfig:
        redirectUrls:
          - https://PM_BASE_DOMAIN:8443/callback*
        # TODO: Default uses a URL without port and using "keycloak" as the service name, not
        # keycloak-service. We override that name further down in this file. Why? Could we not
        # use the default from the Helm chart in both places?
        url: http://keycloak-service.platform-mesh-system.svc.cluster.local:8080/keycloak
      operator:
        enabled: true
        # Keycloak is behind Traefik, which does TLS termination.
        # TODO: Should the default values already set this to true?
        httpEnabled: true
        admin:
          username: keycloak-admin
          # password and secret are supplied by the pre-created keycloak-admin secret (see setup.sh)
        caSecret: domain-certificate-ca
        hostname: https://PM_BASE_DOMAIN:8443/keycloak/
      service:
        name: keycloak-service
        port: 8080
    # TODO: Why does PM seemingly work without these?
    # traefik:
    #   accessControlAllowOriginList:
    #     - http://localhost:4200
    #     - http://localhost:4300
    #     - http://*.localhost:4200
    #     - http://*.localhost:4300
    #     - http://sub.localhost:4300
    #     - https://PM_BASE_DOMAIN:8443
    #     - https://*.PM_BASE_DOMAIN:8443
