apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: init-agent
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: init-agent
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: init-agent
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    kcpKubeconfig: init-agent-kubeconfig
    configWorkspace: root:platform-mesh-system
    hostAliases:
      enabled: true
      values:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
