apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: kubernetes-graphql-gateway
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: kubernetes-graphql-gateway
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: kubernetes-graphql-gateway
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    gatewayApi:
      httpRoute:
        hostnames:
          - PM_BASE_DOMAIN
          - '*.PM_BASE_DOMAIN'
    hostAliases:
      enabled: true
      entries:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
    kubeConfig:
      secretName: kubernetes-graphql-gateway-kubeconfig
    listener:
      # TODO: Where and how? This is nowhere in our Helm charts.
      virtualWorkspacesConfig:
        content:
          virtualWorkspaces:
            - kubeconfig: /app/kubeconfig/kubeconfig
              name: contentconfigurations
              url: https://frontproxy-front-proxy.platform-mesh-system:8443/services/contentconfigurations
            - kubeconfig: /app/kubeconfig/kubeconfig
              name: marketplace
              url: https://frontproxy-front-proxy.platform-mesh-system:8443/services/marketplace
        enabled: true
    trust:
      default:
        audience: default
        jwksUrl: http://keycloak-headless.platform-mesh-system:8080/keycloak/realms/default/protocol/openid-connect/certs
        trustedIssuer: https://PM_BASE_DOMAIN:8443/keycloak/realms/default
