apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: marketplace-ui
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: marketplace-ui
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: marketplace-ui
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    contentConfig:
      baseDomain: PM_BASE_DOMAIN
      protocol: https
    exposure:
      hostnames:
        - PM_BASE_DOMAIN
        - '*.PM_BASE_DOMAIN'
    gatewayApi:
      enabled: true
    http:
      protocol: https
