apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: openfga
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: openfga
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: openfga
  suspend: false
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    checkQueryCache:
      enabled: true
      limit: 10000
      ttl: 10s
    datastore:
      engine: postgres
      maxOpenConns: 30
      migrationType: initContainer
      existingSecret: openfga-datastore-secret
      secretKeys:
        usernameKey: username
        passwordKey: password
    extraEnvVars:
      - name: OPENFGA_EXPERIMENTALS
        value: enable-list-users
      # TODO: This should/can be predefined in the Helm chart now, since it is separated from the credentials.
      - name: OPENFGA_DATASTORE_URI
        value: postgres://platform-mesh-pg-rw.platform-mesh-system.svc.cluster.local:5432/openfga?sslmode=disable
    migrate:
      annotations:
        sidecar.istio.io/inject: "false"
    podAnnotations:
      traffic.sidecar.istio.io/excludeInboundPorts: "2112"
    replicaCount: 1
    telemetry:
      trace:
        enabled: true
        otlp:
          endpoint: observability-opentelemetry-collector.openmfp-observability.svc.cluster.local:4317
          tls:
            enabled: false
