apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: prometheus-operator-crds
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-operator-crds
    namespace: platform-mesh-system
  dependsOn: []
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: prometheus-operator-crds
  targetNamespace: observability
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
