apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: rebac-authz-webhook
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: rebac-authz-webhook
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: rebac-authz-webhook
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    certManager:
      createCA: true
    certificates:
      create: true
    istio:
      # TODO: Has nothing to do with Istio at all, but the cert template in the chart simply
      # uses this field. The cert will also have a wonky IP embedded that we do not care about.
      # Todo is to cleanup the chart a bit and do not use an istio field for a cert that is
      # used without istio.
      dnsNames: [rebac-authz-webhook.platform-mesh-system.svc.cluster.local]
    hostAliases:
      enabled: true
      entries:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
