apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: security-operator
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: security-operator
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: security-operator
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    baseDomain: PM_BASE_DOMAIN:8443
    caSecret: domain-certificate-ca
    idp:
      smtp:
        server: ""
        port: ""
        fromAddress: ""
      additionalRedirectUrls:
        - https://PM_BASE_DOMAIN:8443/callback*
      registrationAllowed: true
      allowUnverifiedEmails: true
      setDefaultPassword: false
    keycloak:
      baseUrl: https://PM_BASE_DOMAIN:8443/keycloak
    hostAliases:
      enabled: true
      entries:
        - ip: TRAEFIK_SERVICE_IP
          hostnames:
            - PM_BASE_DOMAIN
            - kcp.api.PM_BASE_DOMAIN
            - root.kcp.PM_BASE_DOMAIN
            - triton.kcp.PM_BASE_DOMAIN
    kubeconfigSecret: security-operator-kubeconfig
