apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: traefik
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: platform-mesh-system
  dependsOn:
    - name: traefik-crds
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: traefik
  targetNamespace: default
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    experimental:
      kubernetesGateway:
        enabled: true
    gateway:
      enabled: false
    gatewayClass:
      enabled: true
    # image:
    #   registry: registry-1.docker.io
    #   repository: library/traefik
    #   tag: v3.7.12
    ports:
      websecure:
        exposedPort: 8443
        nodePort: 31000
    providers:
      kubernetesGateway:
        enabled: true
        experimentalChannel: true
    service:
      annotations:
        dns.gardener.cloud/class: garden
        dns.gardener.cloud/dnsnames: >-
          pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com,
          *.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com,
          *.services.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com,
          kcp.api.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com,
          root.kcp.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com,
          triton.kcp.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
      spec:
        clusterIP: 100.104.59.216
