apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    core.platform-mesh.io/operator-created: "true"
  name: virtual-workspaces
  namespace: platform-mesh-system
spec:
  chartRef:
    kind: OCIRepository
    name: virtual-workspaces
    namespace: platform-mesh-system
  install:
    remediation:
      retries: -1
  interval: 1m
  releaseName: virtual-workspaces
  targetNamespace: platform-mesh-system
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    hostAliases:
      enabled: true
      entries:
        - ip: 100.104.59.216
          hostnames:
            - pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
            - kcp.api.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
            - root.kcp.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
            - triton.kcp.pm-dev.kcp.shoot.canary.k8s-hana.ondemand.com
